function F=fCriticalValueCase2(mmu,ttheta,i,j,incomeFemale,incomeMale,bbeta,pm,pf,valueMarriageFemaleSecond,...
    valueMarriageMaleSecond)

F=[log(1-mmu)+bbeta*fValueMarriageSecondMale(incomeFemale(i),incomeFemale(j),mmu)-log(incomeMale(j)/...
    (incomeFemale(i)+incomeMale(j)))+ttheta-bbeta*sum(valueMarriageMaleSecond(:,j).*pf');...
    log(incomeFemale(i)/(mmu*(incomeFemale(i)+incomeMale(j))))+...
    bbeta*(sum(valueMarriageFemaleSecond(i,:).*pm)-fValueMarriageSecondFemale(incomeFemale(i),incomeMale(j),...
    mmu))]; 

end
